### PR TITLE
"timeout" #Feature

### PR DESCRIPTION
**Pull request by egyjs**
to make alert appear after some time you can add "timeout" option
```php
$this->alert('success', 'Your answer has been submitted');

$this->alert('info', 'You can update your answer',[
    'timeout' => 4000,
]);
```

### CODE REVIEW

**Comment by dotmarn** [comment]
> to make alert appear after some time you can add "timeout" option
> 
> ```
> $this->alert('success', 'Your answer has been submitted');
> 
> $this->alert('info', 'You can update your answer',[
>     'timeout' => 4000,
> ]);
> ```

Is this different from what is already in the package?
```
$this->alert('info', 'You can update your answer',[
        'timer' => 5000
]);
```

**Comment by egyjs** [comment]
Yes it's . This is delay to appear , `timer` is delay to disappear

**Comment by dotmarn** [comment]
> Yes it's . This is delay to appear , `timer` is delay to disappear

Oh! I see. Good job!!! Is there any use case for this? Just thinking of a reason someone will want to delay notification before showing.

**Comment by egyjs** [comment]
> just thinking of a reason someone will want to delay notification before showing.

case example
```
$this->alert('success', 'Your answer has been submitted');

$this->alert('info', 'You can update your answer',[
    'timeout' => 4000,
]);
```

first we alert  with `success` then wait 4000 ms  and get the `info` alert

**Pull request closed without merging**
